export const GENRES = [
    "Action", "Adventure", "Animation", "Comedy", "Crime",
    "Drama", "Family", "Fantasy", "History",
    "Horror", "Music", "Mystery", "Romance", "Sci-Fi",
    "Thriller", "War", "Western",
];

export const LANGUAGES = {
    "ay": "Aymara",
    "ch": "Chamorro",
    "fj": "Fijian",
    "it": "Italian",
    "nv": "Navajo",
    "qu": "Quechua",
    "ru": "Russian",
    "sc": "Sardinian",
    "sw": "Swahili",
    "tn": "Tswana",
    "ur": "Urdu",
    "ho": "Hiri Motu",
    "km": "Khmer",
    "kj": "Kuanyama",
    "tt": "Tatar",
    "ps": "Pushto",
    "cn": "Cantonese",
    "mk": "Macedonian",
    "yo": "Yoruba",
    "fo": "Faroese",
    "ff": "Fulah",
    "ig": "Igbo",
    "io": "Ido",
    "id": "Indonesian",
    "ko": "Korean",
    "mo": "Moldavian",
    "nr": "Ndebele",
    "pi": "Pali",
    "so": "Somali",
    "sq": "Albanian",
    "ta": "Tamil",
    "tl": "Tagalog",
    "th": "Thai",
    "ve": "Venda",
    "vo": "Volapük",
    "cu": "Slavic",
    "kw": "Cornish",
    "fr": "French",
    "fy": "Frisian",
    "ht": "Haitian; Haitian Creole",
    "ie": "Interlingue",
    "ia": "Interlingua",
    "mh": "Marshall",
    "rn": "Rundi",
    "se": "Northern Sami",
    "gd": "Gaelic",
    "ii": "Yi",
    "lo": "Lao",
    "la": "Latin",
    "ny": "Chichewa; Nyanja",
    "oj": "Ojibwa",
    "ab": "Abkhazian",
    "ar": "Arabic",
    "ee": "Ewe",
    "hi": "Hindi",
    "an": "Aragonese",
    "ba": "Bashkir",
    "bn": "Bengali",
    "bi": "Bislama",
    "et": "Estonian",
    "eu": "Basque",
    "gl": "Galician",
    "ha": "Hausa",
    "hz": "Herero",
    "iu": "Inuktitut",
    "jv": "Javanese",
    "kr": "Kanuri",
    "mn": "Mongolian",
    "my": "Burmese",
    "na": "Nauru",
    "pt": "Portuguese",
    "sd": "Sindhi",
    "zu": "Zulu",
    "ak": "Akan",
    "hu": "Hungarian",
    "ik": "Inupiaq",
    "ks": "Kashmiri",
    "ka": "Georgian",
    "lg": "Ganda",
    "oc": "Occitan",
    "uz": "Uzbek",
    "xh": "Xhosa",
    "za": "Zhuang",
    "zh": "Mandarin",
    "el": "Greek",
    "ga": "Irish",
    "gn": "Guarani",
    "gu": "Gujarati",
    "kl": "Kalaallisut",
    "kn": "Kannada",
    "ky": "Kirghiz",
    "nl": "Dutch",
    "sl": "Slovenian",
    "sr": "Serbian",
    "ss": "Swati",
    "ug": "Uighur",
    "bg": "Bulgarian",
    "co": "Corsican",
    "cy": "Welsh",
    "dv": "Divehi",
    "ki": "Kikuyu",
    "mt": "Maltese",
    "ne": "Nepali",
    "si": "Sinhalese",
    "sn": "Shona",
    "su": "Sundanese",
    "to": "Tonga",
    "wa": "Walloon",
    "cr": "Cree",
    "fi": "Finnish",
    "hr": "Croatian",
    "mg": "Malagasy",
    "nb": "Norwegian Bokmål",
    "ts": "Tsonga",
    "vi": "Vietnamese",
    "hy": "Armenian",
    "av": "Avaric",
    "az": "Azerbaijani",
    "gv": "Manx",
    "sh": "Serbo-Croatian",
    "lv": "Latvian",
    "mr": "Marathi",
    "pl": "Polish",
    "rm": "Raeto-Romance",
    "tr": "Turkish",
    "xx": "No Language",
    "ca": "Catalan",
    "de": "German",
    "rw": "Kinyarwanda",
    "ln": "Lingala",
    "ro": "Romanian",
    "ty": "Tahitian",
    "ti": "Tigrinya",
    "he": "Hebrew",
    "as": "Assamese",
    "bo": "Tibetan",
    "dz": "Dzongkha",
    "eo": "Esperanto",
    "ja": "Japanese",
    "ng": "Ndonga",
    "no": "Norwegian",
    "pa": "Punjabi",
    "sa": "Sanskrit",
    "am": "Amharic",
    "fa": "Persian",
    "aa": "Afar",
    "ae": "Avestan",
    "br": "Breton",
    "is": "Icelandic",
    "kk": "Kazakh",
    "lt": "Lithuanian",
    "mi": "Maori",
    "ms": "Malay",
    "or": "Oriya",
    "st": "Sotho",
    "tk": "Turkmen",
    "af": "Afrikaans",
    "bm": "Bambara",
    "bs": "Bosnian",
    "cs": "Czech",
    "ce": "Chechen",
    "kv": "Komi",
    "lb": "Letzeburgesch",
    "nd": "Ndebele",
    "sk": "Slovak",
    "sm": "Samoan",
    "tg": "Tajik",
    "wo": "Wolof",
    "yi": "Yiddish",
    "be": "Belarusian",
    "cv": "Chuvash",
    "da": "Danish",
    "en": "English",
    "kg": "Kongo",
    "ku": "Kurdish",
    "li": "Limburgish",
    "lu": "Luba-Katanga",
    "ml": "Malayalam",
    "nn": "Norwegian Nynorsk",
    "om": "Oromo",
    "os": "Ossetian; Ossetic",
    "sg": "Sango",
    "es": "Spanish",
    "sv": "Swedish",
    "te": "Telugu",
    "tw": "Twi",
    "uk": "Ukrainian"
};

export const LANGUAGE_OPTIONS = Object.entries(LANGUAGES)
    .map(([value, label]) => ({ value, label }))
    .sort((a, b) => a.label.localeCompare(b.label));
